### PR TITLE
 changed reader to get new object from draw2d object

### PR DESCRIPTION
**Pull request by shaielc**

### CODE REVIEW

**Comment by freegroup** [comment]
thanks for the fix. 

But this will not work. I have a lot of applications which has objects/classes which are not bounded to the "draw2d" package/namespace/whatever. 

Like "company1.eda.restistor". with your approach I'm not able to load this kind of objects.

**Comment by shaielc** [comment]
is it feasable to have an object that will reference all of them?
(and register all of the figureTypes to it)

so as per your example: 
`
figureTypes["company1"] = company1
`
or better
`
figureTypes.register(company1,"company1")
`

**Comment by freegroup** [comment]
unfortunately not - There are a lot of Apps out in production. I don't think, that this is acceptable for the projects to migrate all the save workflows/data to a new shape naming convention.

**Comment by shaielc** [comment]
That doesn't force a change in naming convention
let say I am using 

draw2d.shape.basic.Rectangle
and
company1.eda.restistor

in order to use them in deserialization I would just need to have the static object:
`
{
"draw2d": draw2d,
"company1": company1
}
`
so basically  it will be an object that contains shape namespaces.
and the only change needed is when one creates the shape namespace it would be added to said object.

If i am adding the namespace UML the object will now be:

`
{
"draw2d": draw2d,
"company1": company1
"UML": UML
}
`

**Pull request closed without merging**
